- name: Install Consul agents/clients
  become: yes
  hosts: cc

  tasks:
  - name: Include vars of encryption_keygen into the 'keygen'
    include_vars:
     file: group_vars/encryption_keygen
     name: keygen

  - name: Include vars of agent_token into the 'agent_token'
    include_vars:
     file: "~/.agent_token"
     name: agenttoken
# Install consul
  - name: Include task list in play only if the condition is true
    include: installconsul.yml

# Copy the consul.service file to agents/clients
  - name: Copy config template
    copy:
     src: files/agent_consul.service
     dest: "/etc/systemd/system/consul.service"

# Install unzip
  - name: Install unzip
    apt:
      update_cache: yes
      force_apt_get: yes
      name: unzip
      state: present
# Copy consul binary to server
  - name: Copy consul binary to the servers
    unarchive:
      src: "files/consul/consul_1.7.2_linux_amd64.zip"
      dest: "/usr/bin"
    notify: Install autocomplete-install

# start consul
  - name:  Start consul
    service:
      name: consul
      state: restarted
      enabled: yes
# Install autocomplete-install
  handlers:
  - name: Install autocomplete-install
    become: no
    shell:
      cmd: "consul -autocomplete-install"
