- name: start consul agents/clients
  become: yes
  hosts: cc

  tasks:
  - name: Include vars of encryption_keygen into the 'keygen'
    include_vars:
     file: group_vars/encryption_keygen
     name: keygen

  - name: Include vars of agent_token into the 'agent_token'
    include_vars:
     file: "~/.agent_token"
     name: agenttoken

# Copy consul binary to clients/agents
  - name: Include task list in play only if the condition is true
    include: tasks/installconsul.yml

# Copy config.json template file to agents/clients
  - name: Copy config template
    template:
      src: templates/agent_config_acl.json.j2
      dest: "/etc/consul.d/config.json"
    notify: start consul

# Copy the consul.service file to agents/clients
  - name: Copy config template
    copy:
     src: files/agent_consul.service
     dest: "/etc/systemd/system/consul.service"

# start consul
  - name:  Start consul
    service:
      name: consul
      state: restarted
      enabled: yes

# start consul
  handlers:
  - name: start consul
    service:
     name: consul
     state: restarted
     enabled: yes

# install autocomplete
  - name: start consul
    become: no
    shell:
      cmd: "consul -autocomplete-install"
