- name: Install consul agents/clients
  become: yes
  hosts: consulclients

  tasks:
  - name: Load previously created encryption key from encryption_keygen file & into the 'keygen'
    include_vars:
     file: "{{ tokens_dir }}/encryption_keygen"
     name: keygen

  - name: Load previously created agent_token & load into the 'agent_token'
    include_vars:
     file: "{{ tokens_dir }}/agent_token"
     name: agenttoken

# Copy consul binary to clients/agents
  - name: Include install consul playbook
    include: tasks/installconsul.yml

# Copy config.json template file to agents/clients
  - name: Copy config template
    template:
      src: templates/agent_config_acl.json.j2
      dest: "/etc/consul.d/config.json"
    notify: restart consul

# Copy the consul.service file to agents/clients
  - name: Copy consul.service
    copy:
     src: files/agent_consul.service
     dest: "/etc/systemd/system/consul.service"
    notify: restart consul

# Install autocomplete & restart
  - name: Install autocomplete
    become: no
    shell: "consul -autocomplete-install"
    ignore_errors: yes

  - name: Restart consul
    service:
      name: consul
      state: restarted

#Restart consul
  handlers:
  - name: restart consul
    service:
     name: consul.service
     state: restarted
     enabled: yes
