- name: Install Consul agents/clients
  become: yes
  hosts: cc

  tasks:
  - name: Include vars of encryption_keygen into the 'keygen'
    include_vars:
     file: group_vars/encryption_keygen
     name: keygen

  - name: Include vars of agent_token into the 'keygen'
    include_vars:
     file: "~/.agent_token"
     name: agent_token

# Create consul user and group
  - name: Add group for consul
    group:
     name: consul
     state: present

  - name: Add user for consul
    user:
     name: consul
     groups: consul
     shell: /sbin/nologin
     state: present
     append: yes
     comment: "consul account"

# Create required directories
  - name: create required directories
    file:
     path: "{{ item }}"
     state: directory
     owner: consul
     group: consul
    with_items:
      - /etc/consul.d
      - /consul-data

# Copy config.json template file to server
  - name: Copy config template
    template:
      src: templates/agent_config_acl.json.j2
      dest: "/etc/consul.d/config.json"

# Copy the consul.service file to server
  - name: Copy config template
    copy:
     src: files/agent_consul.service
     dest: "/etc/systemd/system/consul.service"

# Install unzip
  - name: Install unzip
    apt:
      update_cache: yes
      force_apt_get: yes
      name: unzip
      state: present

# Copy consul binary to server
  - name: Copy consul binary to the servers
    unarchive:
      src: "files/consul/consul_1.7.2_linux_amd64.zip"
      dest: "/usr/bin"
    notify: Install autocomplete-install

# start consul
  - name:  Start consul
    service:
      name: consul
      state: restarted
      enabled: yes

# Install autocomplete-install
  handlers:
  - name: Install autocomplete-install
    become: no
    shell:
      cmd: "consul -autocomplete-install"

  - name: Verify consul installation
    shell: "consul --version"
    register: consul_version
  - assert:
     that:
      - "'Consul' in consul_version.stdout"
