# Enable ACL by changing config.json on all servers & rstarting consul service
- hosts: consulservers
  become: yes
  tasks:

# Read previously created encryption key from local file
  - name: Load encryption_keygen token into the 'keygen' var
    include_vars:
     file: "{{ tokens_dir }}/encryption_keygen"
     name: keygen

  - name: Copy new config config.json file with ACL enabled and encryption_keygen included
    template:
      src: templates/config_acl.json.j2
      dest: "/etc/consul.d/config.json"
      force: yes
    notify: reload consul

  handlers:
    - name: reload consul
      service:
       name: consul
       state: restarted
