- name: Install Consul servers
  become: yes
  hosts: cs

  tasks:

  # Copy consul binary to servers
  - name: Include task list in play only if the condition is true
    include: tasks/installconsul.yml

# Create consul keygen 32-bytes, Base64 encoded
  - name: Create new encrytion keygen using shell module
    shell: 'consul keygen'
    run_once: true
    register: keygen

  - name: Print returned keygen json dictionary
    debug:
     var: keygen.stdout

  - name: copy the keygen output to a local file
    copy:
     content: '{{ keygen }}'
     dest: "group_vars/encryption_keygen"
    delegate_to: localhost
    run_once: true

# Copy config.json template file to server
  - name: Copy config.json template
    template:
      src: templates/config.json.j2
      dest: "/etc/consul.d/config.json"

# Copy the consul.service file to server
  - name: Copy consul.service template
    copy:
     src: files/consul.service
     dest: "/etc/systemd/system/consul.service"
    notify: restart consul

# Install autocomplete
  - name: Install autocomplete
    become: no
    shell: "consul -autocomplete-install"
    ignore_errors: yes

  - name: Restart vault
    service:
      name: consul
      state: restarted

# Install autocomplete-install
  handlers:
   - name: restart consul
     service:
       name: consul
       state: restarted
       enabled: yes
