- name: Install Consul servers
  become: yes
  hosts: consulservers

  tasks:

  # Copy consul binary to servers
  - name: Include install consul playbook
    include: tasks/installconsul.yml

# Create consul_tokens_dir
  - name: Create directory for all tokes
    become: no
    file:
      path: "{{ consul_tokens_dir }}"
      state: directory
      mode: '0600'
    delegate_to: localhost

# Create consul keygen 32-bytes, Base64 encoded
  - name: Create new encrytion keygen using shell module
    shell: 'consul keygen'
    run_once: true
    register: keygen

  - name: Print returned keygen json dictionary
    debug:
     var: keygen.stdout

  - name: Write the encryption keygen output to a local file
    become: no
    copy:
     content: '{{ keygen }}'
     dest: "{{consul_tokens_dir}}/encryption_keygen"
    delegate_to: localhost
    run_once: true

# Copy config.json template file to server
  - name: Copy config.json template
    template:
      src: templates/config.json.j2
      dest: "/etc/consul.d/config.json"

# Copy the consul.service file to server
  - name: Copy consul.service template
    copy:
     src: files/consul.service
     dest: "/etc/systemd/system/consul.service"
    notify: restart consul

# Install autocomplete
  - name: Install autocomplete
    become: no
    shell: "consul -autocomplete-install"
    ignore_errors: yes

  - name: Restart vault
    service:
      name: consul
      state: restarted

# Restart Consul
  handlers:
   - name: restart consul
     service:
       name: consul
       state: restarted
       enabled: yes
