- name: Install Consul servers
  become: yes
  hosts: cs

  tasks:

  # Copy consul binary to servers
  - name: Include task list in play only if the condition is true
    include: tasks/installconsul.yml

# consul keygen 32-bytes, Base64 encoded
  - name: Create a new keygen using shell module
    shell: 'consul keygen'
    run_once: true
    register: keygen

  - name: Print returned keygen json dictionary
    debug:
     var: keygen.stdout

  - name: copy the keygen output to a local file
    copy:
     content: '{{ keygen }}'
     dest: "group_vars/encryption_keygen"
    delegate_to: localhost
    run_once: true

# Copy config.json template file to server
  - name: Copy config template
    template:
      src: templates/config.json.j2
      dest: "/etc/consul.d/config.json"

# Copy the consul.service file to server
  - name: Copy config template
    copy:
     src: files/consul.service
     dest: "/etc/systemd/system/consul.service"
    notify: start consul

# Install autocomplete-install
  handlers:
   - name: start consul
     service:
       name: consul
       state: restarted
       enabled: yes

   - name: start consul
     become: no
     shell:
      cmd: "consul -autocomplete-install"
