---
# Warning! Only use this when rebuilding a new cluster.

- name: install consul (ACL not enabled)
  import_playbook: servers_install.yml

# If ACL is not required just run the install playbook or comment out below two

- name: Bootstrap newly installed consul cluster
  import_playbook: consul_bootstrap.yml

- name: install & configure the agents with the right token
  import_playbook: clients_install.yml
