# Vault must be installed, unsealed  and required files already uploaded
# This playbook assumes you used installvault.yml first & preloaded all required files.
# Configures dynamic mysql secrets & ldap
# Creates basic policies for users/devteam (AD groups are via DLAP)
# Adds rootca cert to trusted store
# Selects the first server in your inventory vault server
# Cleans up and deletes all files after config is completed

- name: Configure vault
  hosts: vaultservers[0]

  tasks:

# Load the master_token created in the build/init process into "vault_token"
   - name: Load the master_token created in the build/init process
     become: no
     shell: cat {{ consul_tokens_dir }}/vault_init | grep -e 'Initial Root Token:' | gawk -F '"' '{print $14}' | awk '{print $4}'
     register: vault_token
     delegate_to: localhost

   - name: Print returned vault_token and make token as var
     debug:
      var: vault_token.stdout

# Check if Vault is sealed or not before running the playbook
   - name: Check if Vault is unsealed
     environment:
      VAULT_ADDR: "{{ vault_add }}"
     command: vault status
     register: vault_status_result
     ignore_errors: True

# Fail if sealed
   - name: Print returned vault_status_results and fail if sealed
     fail:
      msg: "FAILED! - Please unseal Vault and then rerun this playbook"
     when: vault_status_result.failed is true

# Enable mysql secrets engine
   - name: Enable secrets engines (Mysql, LDAPS, Transit & SSH key Signing)
     environment:
       VAULT_ADDR: "{{ vault_add }}"
       VAULT_TOKEN: "{{ vault_token.stdout }}"
     command: "{{ item }}"
     with_items:
# Enable mysql secrets engine for temp admin & readonly accounts
     - vault secrets enable mysql
     - vault write mysql/config/connection connection_url="root:root@tcp(192.168.50.180:3306)/"
     - vault write mysql/config/lease lease=5m lease_max=12h
     - vault write {%raw%} mysql/roles/readonly sql="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON *.* TO '{{name}}'@'%';"{%endraw%}
     - vault write {%raw%} mysql/roles/admin sql="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT ALL ON *.* TO '{{name}}'@'%';"{%endraw%}

# Enable transit secrets engine
     - vault secrets enable transit
# Create a named encryption key for transit secret engine
     - vault write -f transit/keys/enc-key

# Enable LDAP and create groups plus policies (dev and admin)
     - vault auth enable ldap
     - vault policy write admin_policy /etc/vault/admin_policy.hcl
     - vault write auth/ldap/groups/users policies=admin_policy
     - vault policy write dev_policy /etc/vault/dev_policy.hcl
     - vault write auth/ldap/groups/devteam policies=dev_policy
     - vault write auth/ldap/config url="ldaps://askartadc01.askarta.local" upndomain="askarta.local"
          userattr=sAMAccountName userdn="OU=HO,DC=askarta,DC=local"
          groupdn="OU=HO,DC=askarta,DC=local" use_token_groups=true
          certificate=@/etc/vault/ldap2021.pem

# SSH Key Signing & Role Configuration
     - vault secrets enable -path=ssh-key-signer ssh
     - vault write ssh-key-signer/roles/appsuport @/etc/vault/appsuport-user-role.hcl
     - vault write ssh-key-signer/roles/ops @/etc/vault/ops-user-role.hcl
     - vault write ssh-key-signer/config/ca generate_signing_key=true

# Download the pulic key and upload to all servers
   - name: Download the pulic key
     shell: curl "{{ vault_add }}"/v1/ssh-key-signer/public_key > trusted-user-ca-keys.pem
     args:
      warn: no

   - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
     fetch:
      src: trusted-user-ca-keys.pem
      dest: ~/
      flat: yes

# Clean up and remove the files that are no longer required
#
- hosts: vaultservers
  become: yes
  tasks:
    - name: Clean up and remove files that are no longer required
      file:
       path: "{{ item }}"
       state: absent
      with_items:
       - trusted-user-ca-keys.pem
       - /etc/vault/admin_policy.hcl
       - /etc/vault/dev_policy.hcl
       - /etc/vault/appsuport-user-role.hcl
       - /etc/vault/ops-user-role.hcl
       - /etc/vault/ldap2021.pem
