- name: Configure vault
  hosts: vaultservers
  become: no
  vars_prompt:

    - name: "Unseal"
      prompt: "Do you want to unseal vault [Yes/No]? [Default is No] "
      default: "no"

  tasks:
    # Read previously created vault tokens from local a file “{{ tokens_dir }}”/vault_init
    - name: Load unseal tokens created in the build/init process
      shell: cat {{ tokens_dir }}/vault_init | awk '/[Unseal]/{print  $4 "\n" $8 "\n" $12}'| sed 's/[",]//g'
      register: unseal_tokens
      delegate_to: localhost

    - name: Print returned unseal_tokens and make them available as a var
      debug:
       var: unseal_tokens.stdout_lines

    - name: Unseal vault with unseal keys
      shell: |
        vault operator unseal {{ item }}
      environment:
        VAULT_ADDR: "{{ vault_add }}"
      with_items: "{{unseal_tokens.stdout_lines}}"
      when: Unseal == "yes"
