- name: Configure vault
  hosts: vaultservers
  become: no

  tasks:
    - name: "Unseal_vault"
      prompt: "Do you want to unseal the cluster [Yes/No]? [Default is No]"
      default: "no"
# Read previously created vault tokens from local file “{{ consul_tokens_dir }}”/vault_init
    - name: Load the master_token created in the build/init process
      shell: cat ~/.consul_tokens/vault_init | awk '/[Unseal]/{print  $4 "\n" $8 "\n" $12}'| sed 's/[",]//g'
      register: vault_tokens
      delegate_to: localhost

    - name: Print returned unseal vault_tokens and make them available as "vault_tokens" var
      debug:
       var: vault_tokens.stdout_lines

    - name: Unseal vault with unseal keys
      shell: |
        vault operator unseal {{ item }}
      environment:
        VAULT_ADDR: "{{ vault_add }}"
      with_items: "{{vault_tokens.stdout_lines}}"
      when: Unseal_vault == yes
