- name: Configure vault
  hosts: vaultservers[0]

  tasks:

# Load the master_token created in the build/init process into "vault_token"
   - name: Load the master_token created in the build/init process
     become: no
     shell: cat {{ consul_tokens_dir }}/vault_init | grep -e 'Initial Root Token:' | gawk -F '"' '{print $14}' | awk '{print $4}'
     register: vault_token
     delegate_to: localhost

   - name: Print returned vault_token and make token as var
     debug:
      var: vault_token.stdout

# Generate PKI and create Intermediate CSR
   - name: Enable PKI secrets engines
     environment:
       VAULT_ADDR: "{{ vault_add }}"
       VAULT_TOKEN: "{{ vault_token.stdout }}"
     command: "{{ item }}"
     with_items:
        - vault secrets enable pki
        - vault secrets tune -max-lease-ttl=87600h pki
        - vault secrets enable -path=pki_int pki
        - vault secrets tune -max-lease-ttl=43800h pki_int
        - vault write '-format=json pki_int/intermediate/generate/internal
            common_name="{{ domain }} Intermediate Authority" | jq -r '.data.csr' > pki_intermediate.csr'




# After CSR is signed please run this command manually to upload signed pub cert
# vault write pki_int/intermediate/set-signed certificate=@intermediate.cert
