- name: Install vault servers
  become: yes
  hosts: cc

  tasks:

# Create vault user and group
  - name: Add group for vault
    group:
     name: vault
     state: present

  - name: Add user for vault
    user:
     name: vault
     groups: vault
     shell: /sbin/nologin
     state: present
     append: yes
     comment: "vault account"

# Create required directories
  - name: create required directories
    file:
     path: "{{ item }}"
     state: directory
     owner: vault
     group: vault
    with_items:
      - /etc/vault
      - /vault-data
      - /logs/vault/

# Copy the binary, vault.service & certs to servers
  - name: Copy config files and certs
    copy: src={{ item.src }} dest={{ item.dest }} owner=root mode=0755
    with_items:
     - { src: 'files/vault.service',  dest: '/etc/systemd/system/vault.service' }
     - { src: 'files/certs.pem', dest: '/etc/vault/certs.pem'}
     - { src: 'files/vaultkey.pem', dest: '/etc/vault/vaultkey.pem'}
     - { src: 'files/vault_1.4.1_linux_amd64', dest: '/usr/bin/vault' }
    notify: start vault

  - name: Copy config.json to servers
    template:
     src: templates/config.json.j2
     dest: "/etc/vault/config.json"
    notify: start vault

#Restart and enable vault service at boot up
  handlers:
   - name: start vault
     service:
      name: vault.service
      state: restarted
      enabled: yes
