- name: Install vault servers
  become: yes
  hosts: cc
  vars_prompt:

  - name: "release_version"
    prompt: "Do you want to initialize the cluster? "
    default: "no"

  tasks:
  - name: Include vars of agent_token into the 'agent_token'
    include_vars:
     file: "~/.agent_token"
     name: agenttoken

# Create vault user and group
  - name: Add group for vault
    group:
     name: vault
     state: present

  - name: Add user for vault
    user:
     name: vault
     groups: vault
     shell: /sbin/nologin
     state: present
     append: yes
     comment: "vault account"

# Create required directories
  - name: create required directories
    file:
     path: "{{ item }}"
     state: directory
     owner: vault
     group: vault
    with_items:
      - /etc/vault
      - /vault-data
      - /logs/vault/

# Copy the binary, vault.service & certs to servers
  - name: Copy config files and certs
    copy: src={{ item.src }} dest={{ item.dest }} owner=root mode=0755
    with_items:
     - { src: 'files/vault.service',  dest: '/etc/systemd/system/vault.service' }
     - { src: 'files/certs.pem', dest: '/etc/vault/certs.pem'}
     - { src: 'files/vaultkey.pem', dest: '/etc/vault/vaultkey.pem'}
     - { src: 'files/vault_1.4.1_linux_amd64', dest: '/usr/bin/vault' }
     - { src: 'files/vault-askarta-local-chain.pem', dest: '/etc/ssl/certs/askarta-pub.pem' }
    notify: restart vault

  - name: Copy config.json to servers
    template:
     src: templates/config.json.j2
     dest: "/etc/vault/config.json"
    notify: restart vault

# Update trusted root certificates
  - name: start vault
    shell: "update-ca-certificates"

  - name: Add env export to .bashrc file
    become: no
    lineinfile:
      path: ~/.bashrc
      line: export VAULT_ADDR=https://vault.askarta.local:8200
      create: yes

  - name: Update hosts file with env export
    lineinfile:
      path: /etc/hosts
      line: "{{ ansible_default_ipv4.address }} vault.askarta.local"
      create: yes

# Vault -autocomplete-install
  - name: start vault
    become: no
    shell: "vault -autocomplete-install"

# Initialize the cluster
  - name: Initialize the cluster using shell module
    shell: 'vault operator init'
    register: vault-init
    when: release_version != no

# Restart and enable vault service at boot up
  handlers:
   - name: restart vault
     service:
      name: vault.service
      state: restarted
      enabled: yes
