- name: Enable mysql secrets engine
  become: yes
  hosts: consulclient1

  tasks:
   - name: Enable mysql secrets engine
     environment:
      VAULT_TOKEN: s.iLfATHpuAcUsIBLpoTaj8RGa
     shell: |
      vault secrets enable mysql
      vault write mysql/config/connection connection_url="root:root@tcp(192.168.50.193:3306)/"
      vault write mysql/config/lease lease=5m lease_max=12h
      vault write mysql/roles/readonly sql="CREATE USER '\{\{name\}\}'@'%' IDENTIFIED BY '\{\{password\}\}';GRANT SELECT ON *.* TO '\{\{name\}\}'@'%';"
      vault write mysql/roles/admin sql="CREATE USER '\{\{name\}\}'@'%' IDENTIFIED BY '\{\{password\}\}';GRANT ALL ON *.* TO '\{\{name\}\}'@'%';"
