- name: Enable mysql secrets engine
  hosts: consulclient1

  tasks:

   - name: Check if Vault is unsealed
     environment:
        VAULT_ADDR: https://vault.askarta.local:8200
     command: vault status
     register: vault_status_result
     ignore_errors: True

   - fail:
      msg: The system may not be provisioned according to the CMDB status.
     when: vault_status_result == "fatal"


   - name: Enable mysql secrets engine
     environment:
      VAULT_ADDR: https://vault.askarta.local:8200
      VAULT_TOKEN: s.rAWYos8uTPiCrEzEFitma1dp
     command: "{{ item }}"
     with_items:
# Enable mysql secrets engine for temp admin & readonly accounts
     - vault secrets enable mysql
     - vault write mysql/config/connection connection_url="root:root@tcp(192.168.50.180:3306)/"
     - vault write mysql/config/lease lease=5m lease_max=12h
     - vault write mysql/roles/readonly sql="CREATE USER '\{\{name\}\}'@'%' IDENTIFIED BY '\{\{password\}\}';GRANT SELECT ON *.* TO '\{\{name\}\}'@'%';"
     - vault write mysql/roles/admin sql="CREATE USER '\{\{name\}\}'@'%' IDENTIFIED BY '\{\{password\}\}';GRANT ALL ON *.* TO '\{\{name\}\}'@'%';"

# Enable transit secrets engine
     - vault secrets enable transit
# Create a named encryption key for transit secret engine
     - vault write -f transit/keys/enc-key
# Enable LDAP and create groups plus policies (dev and admin)
     - vault auth enable ldap
     - vault policy write admin_policy /etc/vault/admin_policy.hcl
     - vault write auth/ldap/groups/users policies=admin_policy
     - vault policy write dev_policy /etc/vault/dev_policy.hcl
     - vault write auth/ldap/groups/devteam policies=dev_policy
     - vault write auth/ldap/config url="ldaps://askartadc01.askarta.local" upndomain="askarta.local"
          userattr=sAMAccountName userdn="OU=HO,DC=askarta,DC=local"
          groupdn="OU=HO,DC=askarta,DC=local" certificate=@/etc/vault/ldap2021.pem
