- name: Enable mysql secrets engine
  hosts: consulclient1
  tasks:

    - name: Check if Vault is unsealed
      environment:
        VAULT_ADDR: https://vault.askarta.local:8200
      command: vault status
      register: vault_status_result
      ignore_errors: False

    - name: Print returned vault_status json dictionary
      debug:
        msg: "Please make sure vault is unsealed" 
      run_once: true
