- name: Enable mysql secrets engine
  hosts: consulclient1
  tasks:

    - name: Check if java is installed
      environment:
        VAULT_ADDR: https://vault.askarta.local:8200
      command: vault status
      register: vault_status_result
      ignore_errors: True

    - name: Print returned vault_status json dictionary
      debug:
        var: vault_status_result.stdout_lines 
      run_once: true
