- name: Enable mysql secrets engine
  hosts: consulclient1
  tasks:

    - name: Check if Vault is unsealed
      environment:
        VAULT_ADDR: https://vault.askarta.local:8200
      command: vault status
      register: vault_status_result
      ignore_errors: True

    - name: fail if vault is sealed
      fail:
        msg: "Vault is sealed"
      when: "'FAILED' in vault_status_result.stderr"


    - name: Print returned vault_status json dictionary
      fail:
       msg: "FAILED - Vault sealed, please unseal it then run this again"
      when: vault_status_result is FAILED


    - debug:
       msg: "Success - Vault unsealed"
      when:  vault_status_result is success
